### PR TITLE
create a variety of 2204 images

### PR DESCRIPTION
**Pull request by aerickson**
Create builders for a variety of 22.04 images. See https://mozilla-hub.atlassian.net/browse/RELOPS-705 for details.
- All are based on https://github.com/taskcluster/community-tc-config/blob/main/imagesets/generic-worker-ubuntu-22-04/bootstrap.sh.

Configurations included in this PR:
```
gw_fxci_gcp_l1_arm64_gui.yaml
gw_fxci_gcp_l1_arm64.yaml
gw_fxci_gcp_l1_gui.yaml
gw_fxci_gcp_l1.yaml
gw_fxci_gcp_l3_arm64.yaml
gw_fxci_gcp_l3_gui.yaml
gw_fxci_gcp_l3.yaml
```

Configs that won't work (multi g-w needs a GUI, https://github.com/taskcluster/taskcluster/issues/6786):

```
gw_fxci_gcp_l1.yaml
gw_fxci_gcp_l3.yaml
gw_fxci_gcp_l1_arm64.yaml
gw_fxci_gcp_l3_arm64.yaml
```

Verified and published configs:

```
gw_fxci_gcp_l1_gui.yaml
gw_fxci_gcp_l3_gui.yaml
gw_fxci_gcp_l1_arm64_gui.yaml
```

Validated with test jobs:
```
gw_fxci_gcp_l1_gui.yaml
```

Also:
- move unused builders into old/ folder
- disable the poetry update check (caused lots of conflicts)

### CODE REVIEW

**Comment by aerickson** [comment]
Building l1/d2g amd64 via `monopacker build gw_fxci_gcp_l1 --secrets_file real_secrets_l1.yaml` at [c27cb2a](https://github.com/mozilla-platform-ops/monopacker/pull/122/commits/c27cb2a83a5ec1c3f96005c45074db9ea9554db5).

Resulting image is `gw-fxci-gcp-l1-googlecompute-2024-01-10t22-16-51z`.

**Comment by aerickson** [comment]
Building l1_gui/Wayland amd64 via `monopacker build gw_fxci_gcp_l1_gui --secrets_file real_secrets_l1.yaml` at [c27cb2a](https://github.com/mozilla-platform-ops/monopacker/pull/122/commits/c27cb2a83a5ec1c3f96005c45074db9ea9554db5).

Resulting image is `gw-fxci-gcp-l1-gui-googlecompute-2024-01-10t22-21-48z`.

**Comment by whimboo** [comment]
Hi @aerickson. One quick question... will the problem with the font cache be solved as well with this version that we are facing for quite some time? To circumvent that we still have the workaround in our [`puppeteer.yml` configuration file](https://searchfox.org/mozilla-central/source/taskcluster/ci/source-test/puppeteer.yml#36). See also https://bugzilla.mozilla.org/show_bug.cgi?id=1670290. I've fixed that once for an older Linux image but then it was missed again.

We notice that given that Puppeteer has a kinda strict timeout restriction and marks tests as failed if they take longer than 20s. Given that no other test suite has that we do not see it for Mochitest, xpcshell etc, but all of them are basically affected in CI.

**Comment by aerickson** [comment]
> Hi @aerickson. One quick question... will the problem with the font cache be solved as well with this version that we are facing for quite some time? To circumvent that we still have the workaround in our [`puppeteer.yml` configuration file](https://searchfox.org/mozilla-central/source/taskcluster/ci/source-test/puppeteer.yml#36). See also https://bugzilla.mozilla.org/show_bug.cgi?id=1670290. I've fixed that once for an older Linux image but then it was missed again.
> 
> We notice that given that Puppeteer has a kinda strict timeout restriction and marks tests as failed if they take longer than 20s. Given that no other test suite has that we do not see it for Mochitest, xpcshell etc, but all of them are basically affected in CI.

I didn't know about that issue (we don't manage docker images). This image could likely have the problem as currently written. 

What is the command to run to generate the cache?

**Comment by whimboo** [comment]
Originally I fixed that on https://bugzilla.mozilla.org/show_bug.cgi?id=1443437 by running the following command:

```
+# use fc-cache:i386 to pre-build the font cache for i386 binaries
+apt-get -q -y -f install \
+    fontconfig:i386 \
```

So we would have to only adjust that for the x86_64 platform.

Also I checked and the problem indeed persists for current Puppeteer jobs:

https://treeherder.mozilla.org/logviewer?job_id=443284896&repo=mozilla-central&lineNumber=242-247

**Comment by aerickson** [comment]
> Originally I fixed that on https://bugzilla.mozilla.org/show_bug.cgi?id=1443437 by running the following command:
> 
> ```
> +# use fc-cache:i386 to pre-build the font cache for i386 binaries
> +apt-get -q -y -f install \
> +    fontconfig:i386 \
> ```
> 
> So we would have to only adjust that for the x86_64 platform.

OK, I will make it happen in the 22.04 Wayland images.

> Also I checked and the problem indeed persists for current Puppeteer jobs:
> 
> https://treeherder.mozilla.org/logviewer?job_id=443284896&repo=mozilla-central&lineNumber=242-247

These jobs are running on a docker-worker instance, so you should be able to specify a docker image in the job that has it fixed (we don't manage docker images). If people keep breaking you, you could create your own image (but not fun to maintain perhaps).

**Comment by aerickson** [comment]
Building l1_gui/Wayland amd64 via `monopacker build gw_fxci_gcp_l1_gui --secrets_file real_secrets_l1.yaml --packer-args '-on-error=ask'` at [574462e](https://github.com/mozilla-platform-ops/monopacker/pull/122/commits/574462ec0e4d025613fd1db6e4b8844f6edd8c59).

Resulting image is `gw-fxci-gcp-l1-gui-googlecompute-2024-01-17t16-39-26z`.

**Comment by aerickson** [comment]
Building l1_gui/Wayland amd64 via `monopacker build gw_fxci_gcp_l1_gui --secrets_file real_secrets_l1.yaml --packer-args '-on-error=ask'` with updated secrets at [ec9b535](https://github.com/mozilla-platform-ops/monopacker/pull/122/commits/ec9b5352369f87351169bf69bd7d556e1531af3f).

Resulting image is `gw-fxci-gcp-l1-gui-googlecompute-2024-01-17t20-25-31z`.

**Comment by aerickson** [comment]
Building l1_gui/Wayland amd64 via `monopacker build gw_fxci_gcp_l1_gui --secrets_file real_secrets_l1.yaml --packer-args '-on-error=ask'` at [c0cb90e](https://github.com/mozilla-platform-ops/monopacker/pull/122/commits/c0cb90e4d528147f548aa8c7e8873173ff1570ae)

Resulting image is `gw-fxci-gcp-l1-gui-googlecompute-2024-01-18t21-28-29z`.

**Comment by aerickson** [comment]
Building l1_gui/Wayland amd64 via monopacker build gw_fxci_gcp_l1_gui --secrets_file real_secrets_l1.yaml --packer-args '-on-error=ask' at [8ae1a21](https://github.com/mozilla-platform-ops/monopacker/pull/122/commits/8ae1a21e3e9542f0ff2e14a5f3952948a09ab4fe).

Resulting image is `gw-fxci-gcp-l1-gui-googlecompute-2024-01-18t23-27-40z`.

**Comment by aerickson** [comment]
Building l1/d2g amd64 via `monopacker build gw_fxci_gcp_l1 --secrets_file real_secrets_l1.yaml` at [8ae1a21](https://github.com/mozilla-platform-ops/monopacker/pull/122/commits/8ae1a21e3e9542f0ff2e14a5f3952948a09ab4fe).

Resulting image is `gw-fxci-gcp-l1-googlecompute-2024-01-19t17-35-11z`.

**Comment by aerickson** [comment]
Building l3/d2g amd64 via `monopacker build gw_fxci_gcp_l3 --secrets_file real_secrets_l3.yaml` at dae3025.

Resulting image is `gw-fxci-gcp-l3-googlecompute-2024-01-19t18-10-08z`.

**Comment by aerickson** [comment]
Building l3_gui/d2g amd64 via `monopacker build gw_fxci_gcp_l3_gui --secrets_file real_secrets_l3.yaml` at e60d2e4.

Resulting image is `gw-fxci-gcp-l3-gui-googlecompute-2024-01-22t18-50-07z`.

**Comment by aerickson** [comment]
Building gw_fxci_gcp_l1_gui with `monopacker build gw_fxci_gcp_l1_gui --secrets_file real_secrets_l1.yaml --packer-args '-on-error=ask'` at 0a40b6.

Resulting image is `gw-fxci-gcp-l1-gui-googlecompute-2024-01-24t19-09-38z`.

**Comment by aerickson** [comment]
Building arm64/l1 GUI with `monopacker build gw_fxci_gcp_l1_arm64_gui --secrets_file real_secrets_l1.yaml` at 10b081d.

Resulting image is `gw-fxci-gcp-l1-arm64-gui-googlecompute-2024-02-14t21-16-11z`.

**Comment by aerickson** [comment]
Building l1_gui/Wayland amd64 via `monopacker build gw_fxci_gcp_l1_gui --secrets_file real_secrets_l1.yaml` at dbe2cf38.

Resulting image is `gw-fxci-gcp-l1-gui-googlecompute-2024-02-14t22-33-57z`.

**Comment by aerickson** [comment]
Building l3_gui/d2g amd64 via `monopacker build gw_fxci_gcp_l3_gui --secrets_file real_secrets_l3.yaml` at dbe2cf38.

Resulting image is `gw-fxci-gcp-l3-gui-googlecompute-2024-02-14t23-01-33z`.

**Comment by aerickson** [comment]
https://phabricator.services.mozilla.com/D201900 makes ci-config use the 3 latest images.

**Review by rcurranmoz — APPROVED** [review]

**Pull request merged**
