### PR TITLE
Local changes for partial Ubuntu 22 support and overall sync

### PR DESCRIPTION
**Pull request by MasterWayZ**
Note; some of these changes may conflict with Community image creation

### CODE REVIEW

**Comment by aerickson** [comment]
@petemoore @lotas @matt-boris Is this repo used by the TC team any longer? OK if we step on community image building?

**Comment by matt-boris** [comment]
> Is this repo used by the TC team any longer? OK if we step on community image building?

We have only used this for building the final docker worker image. We manage our other images in https://github.com/mozilla/community-tc-config. I'd say, go for it. Feel free to do whatever. Would like one more opinion on this though.. @petemoore what do you think?

**Comment by aerickson** [comment]
@petemoore Thoughts?

**Comment by petemoore** [comment]
Absolutely! Let's move this to the [mozilla-platform-ops](https://github.com/mozilla-platform-ops) org.

**Comment by petemoore** [comment]
Created https://bugzilla.mozilla.org/show_bug.cgi?id=1841790

**Comment by aerickson** [comment]
@MasterWayZ should we land this? I'll fix any test failures after.

**Comment by aerickson** [comment]
This was Michelle's work to use docker-worker on 22.04. It never worked (https://mozilla-hub.atlassian.net/browse/RELOPS-356 talks about the issues).

**Review by lotas — APPROVED** [review]

**Comment by aerickson** [comment]
Closing this as we have working 22.04 images.

**Pull request closed without merging**
